<h1>What's New In 2?</h1>
<hr />
<h2>TypeScript</h2>
<p>While TypeScript itself is not a feature of Angular 2, the Angular has fully embraced TypeScript as the preferred language of Angular development. Although Angular can be written in Dart or JavaScript, TypeScript is clearly the direction the Angular team has taken.</p>
<div class="row">
	<div class="col-md-6">
		<h3>JavaScript</h3>
		<div [innerHTML]="todoJs"></div>
	</div>
	<div class="col-md-6">
		<h3>TypeScript</h3>
		<div [innerHTML]="todoTs">
		</div>
	</div>
</div>
<p>While TypeScript is a great language, why learn another language just to use a <em>JavaScript</em> framework!? TypeScript brings to the table strong typing more reminiscent of Java or .NET. It also benefits us with the simplified syntax for building out components such as class inheritance, more expressive closures, and null safety. The preceeding classes are equivalent. In fact, the JavaScript version is automatically generated by the TypeScript compiler.</p>
